version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./sitespeedtools:/var/www/html/wp-content/plugins/sitespeedtools
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8000:80"
    restart: always

  tester:
    build: ./playwright
    depends_on:
      - wordpress
    environment:
      WORDPRESS_URL: "http://wordpress:80"
      WORDPRESS_TITLE: 'Test Site'
      WORDPRESS_ADMIN_USER: 'admin'
      WORDPRESS_ADMIN_PASSWORD: 'MySbXoHchVqBaxJACYc2Uin59KzXfb'
      WORDPRESS_ADMIN_EMAIL: 'test@example.com'
      PLUGIN_NAME: "sitespeedtools"
    volumes:
      - ./videos:/app/videos
      - ./screenshots:/app/screenshots

volumes:
  db_data: {}
  wp_data: {}
