FROM wordpress:latest

# NOTE: WP source files in /usr/src/wordpress/
# On docker-compose up, Docker will load your custom wp-config.php into the
# container and then run the WordPress image's docker-entrypoint.sh which updates
# the file with the values set in your environment variables.

# Enable SSH without authentication on the wordpress container                  
# RUN apt-get update -qq && \
#     apt-get install -yqq openssh-server telnet vim curl less supervisor
# 

